#!/bin/bash
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/timers_and_counters/stim_timer/Makefile
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/timers_and_counters/stim_timer/hd44780.c  
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/timers_and_counters/stim_timer/hd44780.h  
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/timers_and_counters/stim_timer/stim_timer_skel.c
